# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marc/bachelor/CSVM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marc/bachelor/CSVM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marc/bachelor/CSVM/CMakeFiles /home/marc/bachelor/CSVM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marc/bachelor/CSVM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CSVM

# Build rule for target.
CSVM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CSVM
.PHONY : CSVM

# fast build rule for target.
CSVM/fast:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/build
.PHONY : CSVM/fast

src/csvm/csvm_hog_descriptor.o: src/csvm/csvm_hog_descriptor.cc.o
.PHONY : src/csvm/csvm_hog_descriptor.o

# target to build an object file
src/csvm/csvm_hog_descriptor.cc.o:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/csvm/csvm_hog_descriptor.cc.o
.PHONY : src/csvm/csvm_hog_descriptor.cc.o

src/csvm/csvm_hog_descriptor.i: src/csvm/csvm_hog_descriptor.cc.i
.PHONY : src/csvm/csvm_hog_descriptor.i

# target to preprocess a source file
src/csvm/csvm_hog_descriptor.cc.i:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/csvm/csvm_hog_descriptor.cc.i
.PHONY : src/csvm/csvm_hog_descriptor.cc.i

src/csvm/csvm_hog_descriptor.s: src/csvm/csvm_hog_descriptor.cc.s
.PHONY : src/csvm/csvm_hog_descriptor.s

# target to generate assembly for a file
src/csvm/csvm_hog_descriptor.cc.s:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/csvm/csvm_hog_descriptor.cc.s
.PHONY : src/csvm/csvm_hog_descriptor.cc.s

src/csvm/csvm_image_scanner.o: src/csvm/csvm_image_scanner.cc.o
.PHONY : src/csvm/csvm_image_scanner.o

# target to build an object file
src/csvm/csvm_image_scanner.cc.o:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/csvm/csvm_image_scanner.cc.o
.PHONY : src/csvm/csvm_image_scanner.cc.o

src/csvm/csvm_image_scanner.i: src/csvm/csvm_image_scanner.cc.i
.PHONY : src/csvm/csvm_image_scanner.i

# target to preprocess a source file
src/csvm/csvm_image_scanner.cc.i:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/csvm/csvm_image_scanner.cc.i
.PHONY : src/csvm/csvm_image_scanner.cc.i

src/csvm/csvm_image_scanner.s: src/csvm/csvm_image_scanner.cc.s
.PHONY : src/csvm/csvm_image_scanner.s

# target to generate assembly for a file
src/csvm/csvm_image_scanner.cc.s:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/csvm/csvm_image_scanner.cc.s
.PHONY : src/csvm/csvm_image_scanner.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/CSVM.dir/build.make CMakeFiles/CSVM.dir/src/main.cc.s
.PHONY : src/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CSVM"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/csvm/csvm_hog_descriptor.o"
	@echo "... src/csvm/csvm_hog_descriptor.i"
	@echo "... src/csvm/csvm_hog_descriptor.s"
	@echo "... src/csvm/csvm_image_scanner.o"
	@echo "... src/csvm/csvm_image_scanner.i"
	@echo "... src/csvm/csvm_image_scanner.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

