#!/bin/bash
tmp=$(make | grep "100%")

if [ "${tmp#*"Built target"}" == "$tmp" ] ; then
   echo ""
   echo "ERROR found: Execution halted."
   echo ""
else
	if [ $# == 1 ] ; then
		noIters=$1
	else
		noIters=1
	fi

	for i in $(seq 1 $noIters) ;do
   		
   		cd build/
   		logName="LOG"$(date +_%m-%d_%H:%M:%S)
   		echo ""
         echo ""
   		echo "SETTINGS:" >> ./logs/$logName
         echo "" >> ./logs/$logName
         cat settings >> ./logs/$logName
   		echo "" >> ./logs/$logName
         echo "" >> ./logs/$logName
   		./CSVM settings |& tee -a ./logs/$logName
   		echo ""
         echo ""
   		
	done
fi
